import time
import logging
import threading
from pathlib import Path
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler, FileSystemEvent

from gitpilot.config import GitPilotConfig
from gitpilot.pipeline import GitPilotPipeline

logger = logging.getLogger("gitpilot")

class GitEventHandler(FileSystemEventHandler):
    """
    Handles file system events generated by Watchdog.
    Implements a debounce timer so rapid changes result in only one pipeline run.
    """
    
    # Directories and files that should NEVER trigger a commit
    IGNORE_PATHS = {
        ".git",
        "__pycache__",
        "node_modules",
        ".venv",
        "venv",
        "env",
        "build",
        "dist",
        "gitpilot.json",
        "gitpilot.log",
        ".gitpilot_stats.json"
    }

    def __init__(self, repo_path: Path, config: GitPilotConfig, pipeline: GitPilotPipeline, dry_run: bool = False):
        self.repo_path = repo_path
        self.config = config
        self.pipeline = pipeline
        self.dry_run = dry_run
        
        self.timer: threading.Timer = None
        self._lock = threading.Lock()

    def _is_ignored(self, path_str: str) -> bool:
        """Checks if the path contains any ignored directories or files."""
        try:
            # Get relative path from repo root
            rel_path = Path(path_str).relative_to(self.repo_path)
        except ValueError:
            return True # Not in repo

        # Check if any part of the path matches our ignore list
        for part in rel_path.parts:
            if part in self.IGNORE_PATHS:
                return True
        return False

    def _on_event(self, event: FileSystemEvent):
        """Called whenever a file is created, modified, deleted, or moved."""
        if event.is_directory:
            return

        if self._is_ignored(event.src_path):
            return

        # If it's a move event, also check the destination
        if getattr(event, 'dest_path', None) and self._is_ignored(event.dest_path):
            return

        self._reset_timer()

    def on_modified(self, event: FileSystemEvent): self._on_event(event)
    def on_created(self, event: FileSystemEvent): self._on_event(event)
    def on_deleted(self, event: FileSystemEvent): self._on_event(event)
    def on_moved(self, event: FileSystemEvent): self._on_event(event)

    def _reset_timer(self):
        """Resets the debounce timer in a thread-safe way."""
        with self._lock:
            if self.timer:
                self.timer.cancel()
            
            self.timer = threading.Timer(self.config.delay, self._trigger_pipeline)
            self.timer.daemon = True
            self.timer.start()
            logger.info(f"Change detected. Waiting {self.config.delay} seconds for inactivity...")

    def _trigger_pipeline(self):
        """Called when the debounce timer expires."""
        self.pipeline.run(dry_run=self.dry_run)
        logger.info("Watching for changes...")

class GitPilotWatcher:
    """
    Manages the Watchdog Observer.
    """
    def __init__(self, repo_path: Path, config: GitPilotConfig, pipeline: GitPilotPipeline, dry_run: bool = False):
        self.repo_path = repo_path
        self.observer = Observer()
        self.handler = GitEventHandler(repo_path, config, pipeline, dry_run)
        self.observer.schedule(self.handler, str(self.repo_path), recursive=True)

    def start(self):
        """Starts watching the directory."""
        logger.info(f"Watching for changes in {self.repo_path}")
        logger.info(f"Inactivity delay set to {self.handler.config.delay} seconds.")
        self.observer.start()

    def stop(self):
        """Stops watching and cancels any pending timers."""
        logger.info("Stopping GitPilot watcher...")
        self.observer.stop()
        if self.handler.timer:
            self.handler.timer.cancel()
        self.observer.join()
