import time
import logging
import threading
from typing import Optional
from pathlib import Path
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler, FileSystemEvent

from gitpilot.config import GitPilotConfig
from gitpilot.pipeline import GitPilotPipeline
from gitpilot.status import RepositoryState, RepositoryStatus

logger = logging.getLogger("gitpilot")

class GitEventHandler(FileSystemEventHandler):
    """
    Handles file system events generated by Watchdog.
    Implements a debounce timer so rapid changes result in only one pipeline run or status refresh.
    """
    
    IGNORE_PATHS = {
        ".git",
        "__pycache__",
        "node_modules",
        ".venv",
        "venv",
        "env",
        "build",
        "dist",
        "gitpilot.json",
        "gitpilot.log"
    }

    def __init__(self, repo_path: Path, config: GitPilotConfig, pipeline: GitPilotPipeline, dry_run: bool = False, watcher: Optional['GitPilotWatcher'] = None):
        self.repo_path = repo_path
        self.config = config
        self.pipeline = pipeline
        self.dry_run = dry_run
        self.watcher = watcher
        
        self.timer: Optional[threading.Timer] = None
        self._lock = threading.Lock()

    def _is_ignored(self, path_str: str) -> bool:
        """Checks if the path contains any ignored directories or files."""
        try:
            rel_path = Path(path_str).relative_to(self.repo_path)
        except ValueError:
            return True

        for part in rel_path.parts:
            if part in self.IGNORE_PATHS:
                return True
        return False

    def _on_event(self, event: FileSystemEvent):
        """Called whenever a file is created, modified, deleted, or moved."""
        if event.is_directory:
            return

        if self._is_ignored(event.src_path):
            return

        if getattr(event, 'dest_path', None) and self._is_ignored(event.dest_path):
            return

        # Notify monitor of file activity for idle calculation & debouncing
        if hasattr(self.pipeline, 'monitor') and self.pipeline.monitor:
            self.pipeline.monitor.notify_activity()

        self._reset_timer()

    def on_modified(self, event: FileSystemEvent): self._on_event(event)
    def on_created(self, event: FileSystemEvent): self._on_event(event)
    def on_deleted(self, event: FileSystemEvent): self._on_event(event)
    def on_moved(self, event: FileSystemEvent): self._on_event(event)

    def _reset_timer(self):
        """Resets the debounce timer in a thread-safe way."""
        with self._lock:
            if self.timer:
                self.timer.cancel()
            
            self.timer = threading.Timer(self.config.delay, self._trigger_pipeline)
            self.timer.daemon = True
            self.timer.start()
            logger.info(f"Change detected. Waiting {self.config.delay} seconds for inactivity...")

    def _trigger_pipeline(self):
        """Called when the debounce timer expires."""
        if self.watcher and self.watcher.mode == "limited":
            logger.warning("[LIMITED MODE] Changes detected, but automatic commit/push is paused because repository requires synchronization.")
            logger.info("Run 'gitpilot sync' or resolve conflicts manually to enable Active Mode.")
            if hasattr(self.pipeline, 'monitor') and self.pipeline.monitor:
                self.pipeline.monitor.mark_dirty(debounce_sec=1.0)
            return

        self.pipeline.run(dry_run=self.dry_run)
        logger.info("Watching for changes...")


class GitPilotWatcher:
    """
    Manages the Watchdog Observer and coordinates Active vs Limited (Read-Only) watcher modes.
    """
    def __init__(self, repo_path: Path, config: GitPilotConfig, pipeline: GitPilotPipeline, dry_run: bool = False, initial_mode: str = "active"):
        self.repo_path = repo_path
        self.config = config
        self.pipeline = pipeline
        self.mode = initial_mode
        self.observer = Observer()
        
        self.handler = GitEventHandler(repo_path, config, pipeline, dry_run=dry_run, watcher=self)
        self.observer.schedule(self.handler, str(self.repo_path), recursive=True)

        # Register monitor listener callback
        if hasattr(self.pipeline, 'monitor') and self.pipeline.monitor:
            self.pipeline.monitor.register_listener(self._on_status_changed)

    def _on_status_changed(self, status: RepositoryStatus):
        """Callback invoked whenever RepositoryMonitor detects a state change."""
        if status.state in (RepositoryState.UP_TO_DATE, RepositoryState.AHEAD_REMOTE) and not status.has_conflicts:
            if self.mode != "active":
                self.mode = "active"
                logger.info("[OK] Repository synchronized! Watcher automatically promoted to ACTIVE MODE.")
        else:
            if self.mode != "limited":
                self.mode = "limited"
                logger.warning(f"[!] Watcher switched to LIMITED MODE ({status.state.value}). Automatic commits/pushes are paused.")

    def start(self):
        """Starts watching the directory and background fetching."""
        logger.info(f"Watching for changes in {self.repo_path} [Mode: {self.mode.upper()}]")
        logger.info(f"Inactivity delay set to {self.handler.config.delay} seconds.")
        self.observer.start()

        if hasattr(self.pipeline, 'monitor') and self.pipeline.monitor:
            self.pipeline.monitor.start_background_fetch()

    def stop(self):
        """Stops watching, stops background fetch, and cancels timers."""
        logger.info("Stopping GitPilot watcher...")
        if hasattr(self.pipeline, 'monitor') and self.pipeline.monitor:
            self.pipeline.monitor.stop_background_fetch()
            self.pipeline.monitor.unregister_listener(self._on_status_changed)

        self.observer.stop()
        if self.handler.timer:
            self.handler.timer.cancel()
        self.observer.join()
